# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest']
        
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Build Mac OS
      run: |
        bash build_executable_mac.sh
        # Now flag the created file as unix executable
        chmod +x "dist/Nami Beitragsrechner"
        if: matrix.os == 'macos-latest'
    - name: Build Windows OS
      run: |
        powershell build_executable_win.ps1
        if: matrix.os == 'windows-latest'
    - name: Collect Artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: "nami-beitragsrechner"
        path: dist/*
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

