# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'macos-latest']
        
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    - name: Build Mac OS
      if: matrix.os == 'macos-latest'
      run: |
        bash build_executable_mac.sh
    - name: Create Executable
      run: chmod +x "dist/Nami Beitragsrechner"
    - name: Upload Mac OS binaries
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v4
      with:
        name: nami-beitragsrechner-mac
        path: dist/*
    - name: Build Windows OS
      if: matrix.os == 'windows-latest'
      shell: powershell
      run: |
        ./build_executable_win.ps1
    - name: Upload Windows OS binaries
      if: matrix.os == 'windows-latest'
      uses: actions/upload-artifact@v4
      with:
        name: nami-beitragsrechner-win
        path: dist/*.exe
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 src --count --select=E9,F63,F7,F82 --show-source --statistics

